- name: "Global {{ item }}"
  execute_lambda:
    name: '{{ parameters["EnvironmentNameUpper"] }}-glms-health-db'
    payload:
      action: ":migrate"
      payload:
        service: ":{{ parameters['ResourceName'] }}"
        discriminator: ":global"
        realm: ":{{ item }}"
  register: migrate_output
- fail:
    msg: '{{ migrate_output.output }}'
  when: '"error" in migrate_output.result.output'

- name: "Local {{ item }}"
  execute_lambda:
    name: '{{ parameters["EnvironmentNameUpper"] }}-glms-health-db'
    payload:
      action: ":migrate"
      payload:
        service: ":{{ parameters['ResourceName'] }}"
        discriminator: ":local"
        realm: ":{{ item }}"
  register: migrate_output
- fail:
    msg: '{{ migrate_output.output }}'
  when: '"error" in migrate_output.result.output'

